version: "3"
services:
  lychee:
    image: lscr.io/linuxserver/lychee:latest
    container_name: lychee
    # restart: always
    volumes:
      - /opt/docker/lychee/config:/config
      - /opt/docker/lychee/pictures:/pictures
    environment:
      - DB_HOST=192.168.31.37
      - DB_USERNAME=lychee
      - DB_PASSWORD=lychee
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Shanghai
    ports:
      - 90:80
