#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/Scripts/autostart/bspwm.sh

sxhkd &

# 设置多显示器 使用 xrandr -q 或 bspc query -M --names 命令来查看显示器编号。
# I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d  I II III
bspc monitor eDP-1 -d VI VII VIII

bspc config border_width         4
bspc config window_gap           5

bspc config focused_border_color        "#3D37D4"
bspc config normal_border_color         "#839496"
bspc config presel_feedback_color       "#839496"


bspc config initial_polarity    first_child
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a google-chrome focus=on
# bspc rule -a Alacritty
bspc rule -a Rofi state=floating
bspc rule -a st-256color state=floating focus=on
# bspc rule -a Screenkey manage=off


