version: "0.1"
services:
  redis:
    image: redis:6.0.16
    container_name: redis6
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker/redis/data:/var/lib/redis
      - /opt/docker/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    privileged: true