---
version: "0.1"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - TZ=Asia/ShangHai
      - MARIADB_DATABASE=piwigo
      - MARIADB_USER=albert
      - MARIADB_PASSWORD=kylin
      - MARIADB_ROOT_PASSWORD=kylin
    volumes:
      - /opt/docker/mariadb/conf:/etc/mysql/conf.d
      - /opt/docker/mariadb/log:/var/log/mysql
      - /opt/docker/mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
