version: '3'
services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    ports:
      - "6060:80"
    environment:
      - NGINX_PORT=80
    privileged: true
    volumes:
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d
      - /opt/docker/nginx/html:/usr/share/nginx/html
      - /opt/docker/nginx/logs:/var/log/nginx
      - /opt/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
